# Generated by Django 3.1.7 on 2021-04-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=8)),
                ('register_type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=60)),
                ('expense_type', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
