# Generated by Django 3.1.7 on 2021-04-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budge',
            name='date',
            field=models.DateField(),
        ),
    ]
