# Generated by Django 3.1.7 on 2021-04-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210425_0248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense', models.IntegerField()),
                ('register_type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=60)),
                ('expense_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Budge',
        ),
    ]
